name: Build and Release WS Server (release.yml)
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, openbsd]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: |
          output_name=wsserver-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name=${output_name}.exe
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $output_name main.go

      - name: Zip binary
        run: |
          zip_name=wsserver-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          zip -j $zip_name wsserver-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Generate checksum
        id: checksum
        run: |
          zip_name=wsserver-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          sha=$(sha256sum $zip_name | awk '{print $1}')
          echo "checksum=${zip_name}: ${sha}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: wsserver-${{ matrix.goos }}-${{ matrix.goarch }}
          path: wsserver-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    permissions:
      contents: write
      pull-requests: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./binaries

      - name: Display structure of downloaded files
        run: file ./binaries/*/*

      - name: Create versioned GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "WS Server ${{ github.event.inputs.version }}"
          #body_path: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload versioned release assets
        run: |
          for f in ./binaries/*/*.zip; do
            gh release upload ${{ github.event.inputs.version }} "$f" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    permissions:
      contents: read
      pull-requests: read
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./.github/Dockerfile.buildx
          context: .
          push: true
          tags: echothrust/wsserver:latest